// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/config" | "/admin/data" | "/admin/news" | "/admin/participants" | "/admin/payments" | "/admin/team-red" | "/agb" | "/auth/login" | "/auth/verify" | "/challenges" | "/company/dashboard" | "/company/nda" | "/company/register" | "/dashboard" | "/dashboard/proposals" | "/dashboard/sim" | "/dashboard/team-matching" | "/dashboard/votes" | "/data-catalog" | "/data-catalog/[id]" | "/datenschutz" | "/impressum" | "/leg" | "/licensing" | "/proposals" | "/proposals/[id]" | "/proposals/new" | "/register" | "/register/success" | "/register/team-red" | "/safety" | "/security-analysis" | "/snackathons" | "/suggest-role" | "/team" | "/unsubscribe"
type AppRouteHandlerRoutes = "/api/admin/announcements" | "/api/admin/bootstrap" | "/api/admin/config" | "/api/admin/data" | "/api/admin/participants" | "/api/admin/payments" | "/api/admin/stats" | "/api/announcements" | "/api/auth/logout" | "/api/auth/magic-link" | "/api/auth/session" | "/api/auth/verify" | "/api/calendar/event" | "/api/companies" | "/api/companies/nda" | "/api/compute" | "/api/compute/[jobId]" | "/api/config" | "/api/cron/check-event-status" | "/api/data-catalog" | "/api/funds" | "/api/heat/credits" | "/api/heat/settle" | "/api/heat/stats" | "/api/notifications" | "/api/participants/me" | "/api/proposals" | "/api/proposals/[id]" | "/api/proposals/[id]/vote" | "/api/sim/dev/file" | "/api/sim/runs" | "/api/sim/runs/[id]" | "/api/sim/runs/[id]/cancel" | "/api/sim/webhook/complete" | "/api/snackathons/checkout" | "/api/storage" | "/api/stripe/checkout" | "/api/stripe/webhook" | "/api/submit-resource" | "/api/subscribe" | "/api/suggest-role" | "/api/team-matching" | "/api/team-matching/request" | "/api/team-matching/respond" | "/api/team-red/apply" | "/api/test-email" | "/api/unsubscribe" | "/api/upload"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/config": {}
  "/admin/data": {}
  "/admin/news": {}
  "/admin/participants": {}
  "/admin/payments": {}
  "/admin/team-red": {}
  "/agb": {}
  "/api/admin/announcements": {}
  "/api/admin/bootstrap": {}
  "/api/admin/config": {}
  "/api/admin/data": {}
  "/api/admin/participants": {}
  "/api/admin/payments": {}
  "/api/admin/stats": {}
  "/api/announcements": {}
  "/api/auth/logout": {}
  "/api/auth/magic-link": {}
  "/api/auth/session": {}
  "/api/auth/verify": {}
  "/api/calendar/event": {}
  "/api/companies": {}
  "/api/companies/nda": {}
  "/api/compute": {}
  "/api/compute/[jobId]": { "jobId": string; }
  "/api/config": {}
  "/api/cron/check-event-status": {}
  "/api/data-catalog": {}
  "/api/funds": {}
  "/api/heat/credits": {}
  "/api/heat/settle": {}
  "/api/heat/stats": {}
  "/api/notifications": {}
  "/api/participants/me": {}
  "/api/proposals": {}
  "/api/proposals/[id]": { "id": string; }
  "/api/proposals/[id]/vote": { "id": string; }
  "/api/sim/dev/file": {}
  "/api/sim/runs": {}
  "/api/sim/runs/[id]": { "id": string; }
  "/api/sim/runs/[id]/cancel": { "id": string; }
  "/api/sim/webhook/complete": {}
  "/api/snackathons/checkout": {}
  "/api/storage": {}
  "/api/stripe/checkout": {}
  "/api/stripe/webhook": {}
  "/api/submit-resource": {}
  "/api/subscribe": {}
  "/api/suggest-role": {}
  "/api/team-matching": {}
  "/api/team-matching/request": {}
  "/api/team-matching/respond": {}
  "/api/team-red/apply": {}
  "/api/test-email": {}
  "/api/unsubscribe": {}
  "/api/upload": {}
  "/auth/login": {}
  "/auth/verify": {}
  "/challenges": {}
  "/company/dashboard": {}
  "/company/nda": {}
  "/company/register": {}
  "/dashboard": {}
  "/dashboard/proposals": {}
  "/dashboard/sim": {}
  "/dashboard/team-matching": {}
  "/dashboard/votes": {}
  "/data-catalog": {}
  "/data-catalog/[id]": { "id": string; }
  "/datenschutz": {}
  "/impressum": {}
  "/leg": {}
  "/licensing": {}
  "/proposals": {}
  "/proposals/[id]": { "id": string; }
  "/proposals/new": {}
  "/register": {}
  "/register/success": {}
  "/register/team-red": {}
  "/safety": {}
  "/security-analysis": {}
  "/snackathons": {}
  "/suggest-role": {}
  "/team": {}
  "/unsubscribe": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
