// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/config">> = Specific
  const handler = {} as typeof import("../../../app/admin/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data">> = Specific
  const handler = {} as typeof import("../../../app/admin/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/news">> = Specific
  const handler = {} as typeof import("../../../app/admin/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/participants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/participants">> = Specific
  const handler = {} as typeof import("../../../app/admin/participants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../../app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/team-red/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/team-red">> = Specific
  const handler = {} as typeof import("../../../app/admin/team-red/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/agb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agb">> = Specific
  const handler = {} as typeof import("../../../app/agb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify">> = Specific
  const handler = {} as typeof import("../../../app/auth/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/challenges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/challenges">> = Specific
  const handler = {} as typeof import("../../../app/challenges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/company/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/company/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/company/nda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/nda">> = Specific
  const handler = {} as typeof import("../../../app/company/nda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/company/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/register">> = Specific
  const handler = {} as typeof import("../../../app/company/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/proposals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/proposals">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/proposals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/sim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sim">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/sim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/team-matching/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/team-matching">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/team-matching/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/votes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/votes">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/votes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/data-catalog/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-catalog/[id]">> = Specific
  const handler = {} as typeof import("../../../app/data-catalog/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/data-catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-catalog">> = Specific
  const handler = {} as typeof import("../../../app/data-catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/datenschutz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datenschutz">> = Specific
  const handler = {} as typeof import("../../../app/datenschutz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/impressum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/impressum">> = Specific
  const handler = {} as typeof import("../../../app/impressum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/leg/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leg">> = Specific
  const handler = {} as typeof import("../../../app/leg/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/licensing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/licensing">> = Specific
  const handler = {} as typeof import("../../../app/licensing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/proposals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../../app/proposals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/proposals/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proposals/new">> = Specific
  const handler = {} as typeof import("../../../app/proposals/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/proposals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proposals">> = Specific
  const handler = {} as typeof import("../../../app/proposals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/success">> = Specific
  const handler = {} as typeof import("../../../app/register/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register/team-red/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/team-red">> = Specific
  const handler = {} as typeof import("../../../app/register/team-red/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/safety/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safety">> = Specific
  const handler = {} as typeof import("../../../app/safety/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-analysis">> = Specific
  const handler = {} as typeof import("../../../app/security-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/snackathons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/snackathons">> = Specific
  const handler = {} as typeof import("../../../app/snackathons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/suggest-role/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suggest-role">> = Specific
  const handler = {} as typeof import("../../../app/suggest-role/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../../app/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/unsubscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../../app/unsubscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bootstrap">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/config">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/data">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/participants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/participants">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/participants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements">> = Specific
  const handler = {} as typeof import("../../../app/api/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/magic-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-link">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/magic-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/calendar/event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/event">> = Specific
  const handler = {} as typeof import("../../../app/api/calendar/event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/companies/nda/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/companies/nda">> = Specific
  const handler = {} as typeof import("../../../app/api/companies/nda/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/companies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/companies">> = Specific
  const handler = {} as typeof import("../../../app/api/companies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compute/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compute/[jobId]">> = Specific
  const handler = {} as typeof import("../../../app/api/compute/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compute">> = Specific
  const handler = {} as typeof import("../../../app/api/compute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config">> = Specific
  const handler = {} as typeof import("../../../app/api/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/check-event-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/check-event-status">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/check-event-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-catalog">> = Specific
  const handler = {} as typeof import("../../../app/api/data-catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/funds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/funds">> = Specific
  const handler = {} as typeof import("../../../app/api/funds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/heat/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heat/credits">> = Specific
  const handler = {} as typeof import("../../../app/api/heat/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/heat/settle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heat/settle">> = Specific
  const handler = {} as typeof import("../../../app/api/heat/settle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/heat/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heat/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/heat/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/participants/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/participants/me">> = Specific
  const handler = {} as typeof import("../../../app/api/participants/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/proposals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/proposals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/proposals/[id]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[id]/vote">> = Specific
  const handler = {} as typeof import("../../../app/api/proposals/[id]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals">> = Specific
  const handler = {} as typeof import("../../../app/api/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sim/dev/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sim/dev/file">> = Specific
  const handler = {} as typeof import("../../../app/api/sim/dev/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sim/runs/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sim/runs/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/sim/runs/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sim/runs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sim/runs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/sim/runs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sim/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sim/runs">> = Specific
  const handler = {} as typeof import("../../../app/api/sim/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sim/webhook/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sim/webhook/complete">> = Specific
  const handler = {} as typeof import("../../../app/api/sim/webhook/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/snackathons/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/snackathons/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/snackathons/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/storage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/storage">> = Specific
  const handler = {} as typeof import("../../../app/api/storage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../../app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/submit-resource/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit-resource">> = Specific
  const handler = {} as typeof import("../../../app/api/submit-resource/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribe">> = Specific
  const handler = {} as typeof import("../../../app/api/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/suggest-role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suggest-role">> = Specific
  const handler = {} as typeof import("../../../app/api/suggest-role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/team-matching/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team-matching/request">> = Specific
  const handler = {} as typeof import("../../../app/api/team-matching/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/team-matching/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team-matching/respond">> = Specific
  const handler = {} as typeof import("../../../app/api/team-matching/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/team-matching/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team-matching">> = Specific
  const handler = {} as typeof import("../../../app/api/team-matching/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/team-red/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team-red/apply">> = Specific
  const handler = {} as typeof import("../../../app/api/team-red/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-email">> = Specific
  const handler = {} as typeof import("../../../app/api/test-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unsubscribe">> = Specific
  const handler = {} as typeof import("../../../app/api/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
